apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhttpd-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myhttpd
  template:
    metadata:
      labels:
        app: myhttpd
    spec:
      containers:
      - name: myhttpd-pod
        image: 211.183.3.10:5000/myhttpd:7
        ports:
        - containerPort: 8085
        command: ["java", "-jar", "springbootApp.jar"]
---
apiVersion: v1
kind: Service
metadata:
  name: myhttpd-svc
spec:
  type: NodePort
  selector:
    app: myhttpd
  ports:
    - protocol: TCP
      port: 32100
      targetPort: 8085
      nodePort: 32100
